#!/bin/sh

echo -e '\n***** Fetching new version from GitHub *****\n\n'
git fetch
git pull

echo -e '\n***** Installing dependencies *****\n\n'
yarn

echo -e '\n***** Migrating Database *****\n\n'
npx sequelize db:migrate

echo -e '\n***** Restarting PM2 *****\n\n'
pm2 restart codimd-bytecode

echo -e '\n***** Deployment done *****\n\n'

echo -e '\n***** For building the front-end, run `yarn run build` *****\n\n'
