#!/bin/sh

echo '\n***** Fetching new version from GitHub *****\n\n'
git fetch
git pull

echo '\n***** Installing dependencies *****\n\n'
yarn

echo '\n***** Building front-end *****\n\n'
yarn run build

echo '\n***** Migrating Database *****\n\n'
npx sequelize db:migrate

echo '\n***** Restarting PM2 *****\n\n'
pm2 restart codimd-bytecode
